### ISSUE TITLE
Blast API sids list

### ISSUE THREAD

**Issue by robmoffat** [finos/symphony-api-spec#102]
According to the documentation, the list of sids for the blast API should be comma-separated.  And, if the swagger looks like this:

```

// line 373, agent api (deprecated version)
       - name: sids
          description: A comma-separated list of Stream IDs
          in: formData
          required: true
          type: string
```

... all is well.

However, at the moment, the swagger seems to look for a list of strings, which doesn't appear to be supported in my version of Jersey:

```
       - name: sids
          description: A comma-separated list of Stream IDs
          in: formData
          required: true
          type: array
          items:
            type: string  // doesn't seem supported in Jersey?
```

Is this a mistake in the api, or intentional?  It seems like it might be a mistake, given  that the description asks for a comma-separated list.
